heat_template_version: 2017-02-24

parameters:
  key_name:
    type: string
    description: Name of a KeyPair
    default: keypair
  flavor_name:
    type: string
    description: Name of a Flavor
    default: sktel.small
  image_name:
    type: string
    description: Name of an Image
    default: cirros

resources:
  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image_name }
      flavor: { get_param: flavor_name }
      networks: 
        - network: public
      security_groups:
        - default
