heat_template_version: 2017-02-24

parameters:
  key_name:
    type: string
    description: Name of a KeyPair
  flavor_name:
    type: string
    description: Name of a Flavor
  image_name:
    type: string
    description: Name of an Image
  vnf_image_name:
    type: string
    description: Name of a VNF image
  tenant1_cidr:
    type: string
    description: CIDR for Tenant 1
  tenant2_cidr:
    type: string
    description: CIDR for Tenant 2

resources:
  tenant1:
    type: https://raw.githubusercontent.com/ShawnClake/OpenStack-Heat-Templates/sasktel-sandbox/sasktel-sandbox/2i_1n.yaml
    properties:
      key_name: { get_param: key_name }
      flavor_name: { get_param: flavor_name }
      image_name: { get_param: image_name }
      subnet_cidr: { get_param: tenant1_cidr }

  tenant2:
    type: https://raw.githubusercontent.com/ShawnClake/OpenStack-Heat-Templates/sasktel-sandbox/sasktel-sandbox/2i_1n.yaml
    properties:
      key_name: { get_param: key_name }
      flavor_name: { get_param: flavor_name }
      image_name: { get_param: image_name }
      subnet_cidr: { get_param: tenant2_cidr }
      
  tenant1_gateway_port:
    type: OS::Neutron::Port
    properties:
      network: { get_attr: [tenant1, resource.internal_net] }
      fixed_ips:
        - subnet: { get_attr: [tenant1, resource.internal_subnet] }
        - ip_address: { get_attr: [tenant1, resource.internal_subnet, gateway_ip] }
        
  tenant2_gateway_port:
    type: OS::Neutron::Port
    properties:
      network: { get_attr: [tenant2, resource.internal_net] }
      fixed_ips:
        - subnet: { get_attr: [tenant2, resource.internal_subnet] }
        - ip_address: { get_attr: [tenant2, resource.internal_subnet, gateway_ip] }

  vnf-server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      flavor: { get_param: flavor_name }
      image: { get_param: vnf_image_name }
      networks: 
        - network: provider_network
        - port: { get_resource: tenant1_gateway_port }
        - port: { get_resource: tenant2_gateway_port }
      security_groups:
        - default
        - ssh
        - vnc
        - ping



