heat_template_version: 2017-02-24

parameters:
  key_name:
    type: string
    description: Name of a KeyPair
    default: keypair
  flavor_name:
    type: string
    description: Name of a Flavor
    default: sktel.small
  image_name:
    type: string
    description: Name of an Image
    default: cirros
  vnf_image_name:
    type: string
    description: Name of a VNF image
    default: vyos
  tenant1_cidr:
    type: string
    description: CIDR for Tenant 1
    default: 172.16.84.0/24
  tenant2_cidr:
    type: string
    description: CIDR for Tenant 2
    default: 172.16.126.0/24
  tnet_cidr:
    type: string
    description: CIDR for TNet
    default: 172.16.168.0/24

resources:
  tenant1:
    type: https://raw.githubusercontent.com/ShawnClake/OpenStack-Heat-Templates/sasktel-sandbox/sasktel-sandbox/2i_1n.yaml
    properties:
      key_name: { get_param: key_name }
      flavor_name: { get_param: flavor_name }
      image_name: { get_param: image_name }
      subnet_cidr: { get_param: tenant1_cidr }

  tenant2:
    type: https://raw.githubusercontent.com/ShawnClake/OpenStack-Heat-Templates/sasktel-sandbox/sasktel-sandbox/2i_1n.yaml
    properties:
      key_name: { get_param: key_name }
      flavor_name: { get_param: flavor_name }
      image_name: { get_param: image_name }
      subnet_cidr: { get_param: tenant2_cidr }
      
  tenant1_gateway_port:
    type: OS::Neutron::Port
    properties:
      network: { get_attr: [tenant1, resource.internal_net] }
      fixed_ips:
        - ip_address: { get_attr: [tenant1, resource.internal_subnet, gateway_ip] }
      port_security_enabled: false
        
  tenant2_gateway_port:
    type: OS::Neutron::Port
    properties:
      network: { get_attr: [tenant2, resource.internal_net] }
      fixed_ips:
        - ip_address: { get_attr: [tenant2, resource.internal_subnet, gateway_ip] }
      port_security_enabled: false
      
  tnet:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false

  tnet_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: tnet }
      cidr: { get_param: tnet_cidr }
      ip_version: 4
        
  tnet_port1:
    type: OS::Neutron::Port
    properties:
      network: tnet
      security_groups:
        - open
        
  tnet_port2:
    type: OS::Neutron::Port
    properties:
      network: tnet
      security_groups:
        - open
        
  trouter:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: provider_network }

  trouter_interface1:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: trouter }
      subnet: { get_resource: tnet_subnet }

  vnf-server1:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      flavor: { get_param: flavor_name }
      image: { get_param: vnf_image_name }
      networks: 
        - port: { get_resource: tnet }
        - port: { get_resource: tenant1_gateway_port }
        
  vnf-server2:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      flavor: { get_param: flavor_name }
      image: { get_param: vnf_image_name }
      networks: 
        - port: { get_resource: tnet }
        - port: { get_resource: tenant2_gateway_port }
